using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EnemyType { 
   SLOW_WALKER,
   MEDIUM_WALKER,
   FAST_WALKER,
   SLOW_AIR,
   MEDIUM_AIR,
   FAST_AIR,
   SLOW_WALKER_2SHOTS,
   SLOW_WALKER_1SHOTS_UNPREDICTABLE,
   MEDIUM_WALKER_2SHOTS,
   MEDIUM_WALKER_1SHOTS_UNPREDICTABLE,
   FAST_WALKER_2SHOTS,
   FAST_WALKER_1SHOTS_UNPREDICTABLE,
   FAST_AIR_1SHOTS_UNPREDICTABLE
}
